subdomains:
  ruby:
    title: Ruby Resources
    description: TODO
    additional_stylesheets:
      - href: http://fonts.googleapis.com/css?family=Noto+Sans
    styling:
      bg_color: "#ebebe5"
      text_color: black
      font_family: "'Noto Sans', 'Helvetica Neue', Helvetica, sans-serif"
      header:
        logo_img_src: logos/ruby.png
        bg_color: white
        text_color: black
      resource_block:
        background_color: "rgba(0,0,0,0.1)"
    resources:
      - title: Ruby Lang
        links:
          - url: http://www.ruby-lang.org
            type: site
        description: The official Ruby web site.
        screenshot_img_src: screenshots/ruby/ruby-lang.png
      - title: Ruby Rogues
        links:
          - url: http://rubyrogues.com
            type: site
        description: An awesome weekly podcast discussing everything Ruby related.
        screenshot_img_src: screenshots/ruby/ruby-rogues.png
      - title: rubyflow
        links:
          - url: http://www.rubyflow.com
            type: site
        description: 
        screenshot_img_src: screenshots/ruby/rubyflow.jpg
      - title: afreshcup
        links:
          - url: http://afreshcup.com
            type: site
        description: 
        screenshot_img_src: screenshots/ruby/afreshcup.jpg
      - title: railstips
        links:
          - url: http://www.railstips.org
            type: site
        description: 
        screenshot_img_src: screenshots/ruby/railstips.jpg
      - title: planetrubyonrails
        links:
          - url: http://planetrubyonrails.com
            type: site
        description: 
        screenshot_img_src: screenshots/ruby/planetrubyonrails.jpg
      - title: ruby5
        links:
          - url: http://ruby5.envylabs.com
            type: site
        description: 
        screenshot_img_src: screenshots/ruby/ruby5.jpg
      - title: greenruby
        links:
          - url: http://greenruby.org
            type: site
        description: 
        screenshot_img_src: screenshots/ruby/greenruby.jpg
      - title: Monkey and Crow
        links:
          - url: http://monkeyandcrow.com
            type: site
        description: 
        screenshot_img_src: screenshots/ruby/monkeyandcrow.jpg
      - title: Ruby Weekly
        links:
          - url: http://rubyweekly.com
            type: site
        description: 
        screenshot_img_src: screenshots/ruby/rubyweekly.jpg
      - title: Arkency Blog
        links:
          - url: http://blog.arkency.com
            type: site
        description: 
        screenshot_img_src: screenshots/ruby/arkency.jpg
      - title: chodounsky
        links:
          - url: http://chodounsky.net
            type: site
        description: 
        screenshot_img_src: screenshots/ruby/chodounsky.jpg

  node:
    title: Node Resources
    description: TODO
    additional_stylesheets:
      - href: http://fonts.googleapis.com/css?family=Source+Sans+Pro
    styling:
      bg_color: "#1d1d1d"
      text_color: "#ccc"
      font_family: "'source-sans-pro', sans-serif"
      header:
        logo_img_src: logos/node.png
        bg_color: "#303030"
        text_color: "#ccc"
      resource_block:
        background_color: "rgba(255,255,255,0.1)"
    resources:
      - title: Node
        links:
          - url: http://nodejs.org
            type: site
        description: The official NodeJs web site.
        screenshot_img_src: screenshots/node/nodejs.jpg
