subdomains:
  ruby:
    title: Ruby Resources
    description: TODO
    additional_stylesheets:
      - href: http://fonts.googleapis.com/css?family=Noto+Sans
    styling:
      bg_color: "#ebebe5"
      text_color: black
      font_family: "'Noto Sans', 'Helvetica Neue', Helvetica, sans-serif"
      header:
        logo_img_src: logos/ruby.png
        bg_color: white
        text_color: black
      resource_block:
        background_color: "rgba(0,0,0,0.1)"
        background_hover_color: "rgba(0,0,0,0.2)"
    resources:
      - title: Ruby Lang
        description: The official Ruby web site.
        screenshot_img_src: screenshots/ruby/ruby-lang.png
        url: http://www.ruby-lang.org/en/
      - title: Ruby Rogues
        description: An awesome weekly podcast discussing everything Ruby related.
        screenshot_img_src: screenshots/ruby/ruby-rogues.png
        url: http://rubyrogues.com/
      - title: rubyflow
        description: 
        screenshot_img_src: screenshots/ruby/rubyflow.jpg
        url: http://www.rubyflow.com
      - title: afreshcup
        description: 
        screenshot_img_src: screenshots/ruby/afreshcup.jpg
        url: http://afreshcup.com
      - title: railstips
        description: 
        screenshot_img_src: screenshots/ruby/railstips.jpg
        url: http://www.railstips.org
      - title: planetrubyonrails
        description: 
        screenshot_img_src: screenshots/ruby/planetrubyonrails.jpg
        url: http://planetrubyonrails.com
      - title: ruby5
        description: 
        screenshot_img_src: screenshots/ruby/ruby5.jpg
        url: http://ruby5.envylabs.com
      - title: greenruby
        description: 
        screenshot_img_src: screenshots/ruby/greenruby.jpg
        url: http://greenruby.org/
      - title: Monkey and Crow
        description: 
        screenshot_img_src: screenshots/ruby/monkeyandcrow.jpg
        url: http://monkeyandcrow.com
      - title: Ruby Weekly
        description: 
        screenshot_img_src: screenshots/ruby/rubyweekly.jpg
        url: http://rubyweekly.com
      - title: Arkency Blog
        description: 
        screenshot_img_src: screenshots/ruby/arkency.jpg
        url: http://blog.arkency.com
      - title: chodounsky
        description: 
        screenshot_img_src: screenshots/ruby/chodounsky.jpg
        url: http://chodounsky.net

  node:
    title: Node Resources
    description: TODO
    additional_stylesheets:
      - href: http://fonts.googleapis.com/css?family=Source+Sans+Pro
    styling:
      bg_color: "#1d1d1d"
      text_color: "#ccc"
      font_family: "'source-sans-pro', sans-serif"
      header:
        logo_img_src: logos/node.png
        bg_color: "#303030"
        text_color: "#ccc"
      resource_block:
        background_color: "rgba(255,255,255,0.1)"
        background_hover_color: "rgba(255,255,255,0.2)"
    resources:
      - title: Node
        description: The official NodeJs web site.
        screenshot_img_src: screenshots/node/nodejs.jpg
        url: http://nodejs.org
