subdomains:
  ruby:
    title: Ruby Resources
    description: TODO
    additional_stylesheets:
      - href: http://fonts.googleapis.com/css?family=Noto+Sans
    styling:
      bg_color: "#ebebe5"
      text_color: black
      font_family: "'Noto Sans', 'Helvetica Neue', Helvetica, sans-serif"
      header:
        logo_img_src: logos/ruby.png
        bg_color: white
        text_color: black
      resource_block:
        background_color: "rgba(0,0,0,0.1)"
    resources:
      - title: Ruby Lang
        links:
          - url: http://www.ruby-lang.org
            type: site
        description: The canonical Ruby resource. Home of the Ruby language documentation, as well as a wealth of links to news sources, libraries, and user groups.
        screenshot_img_src: screenshots/ruby/ruby-lang.png
      - title: Ruby On Rails
        links:
          - url: http://rubyonrails.org
            type: site
          - url: http://weblog.rubyonrails.org
            type: blog
        description: There is a good chance that you were introduced to Ruby through Ruby on Rails, a popular web framework.
        screenshot_img_src: screenshots/ruby/rails.jpg
      - title: Try Ruby
        links:
          - url: http://tryruby.org
            type: site
        description: The single best place to try ruby for the first time. You can take lessons and type code right in your browser.
        screenshot_img_src: screenshots/ruby/try-ruby.jpg
      - title: CODETUNES
        links:
          - url: http://codetunes.com
            type: blog
        description: The blog of Monterail, a rails dev shop in Poland. They frequently post quality content, and I love the simplicity of the site.
        screenshot_img_src: screenshots/ruby/codetunes.jpg
      - title: Ruby Rogues
        links:
          - url: http://rubyrogues.com
            type: podcast
        description: An awesome weekly podcast discussing anything Ruby related. These guys do an awesome job transcribing each episode into text, as well as providing links to everything mentioned on the show.
        screenshot_img_src: screenshots/ruby/ruby-rogues.png
      - title: Ruby Inside
        links:
          - url: http://www.rubyinside.com
            type: blog
        description: The blog has not been updated since July 2013 but their newsletter and twitter account still seem to alive and kicking.
        screenshot_img_src: screenshots/ruby/ruby-inside.jpg
      - title: Planet Ruby
        links:
          - url: http://planetruby.0x42.net
            type: blog
        description: 
        screenshot_img_src: screenshots/ruby/planey-ruby.jpg
      - title: Planet RubyOnRails
        links:
          - url: http://www.planetrubyonrails.org
            type: blog
        description: 
        screenshot_img_src: screenshots/ruby/planey-ruby-on-rails.jpg
      - title: Destroy All Software
        links:
          - url: http://www.destroyallsoftware.com
            type: screencasts
        description: 
        screenshot_img_src: screenshots/ruby/destroy-all-software.jpg
      - title: Ruby Corner
        links:
          - url: http://rubycorner.com
            type: blog
        description: 
        screenshot_img_src: screenshots/ruby/ruby-corner.jpg
      - title: RailsCasts
        links:
          - url: http://railscasts.com
            type: screencasts
        description: 
        screenshot_img_src: screenshots/ruby/rails-casts.jpg
      - title: RubyFlow
        links:
          - url: http://www.rubyflow.com
            type: blog
        description: 
        screenshot_img_src: screenshots/ruby/rubyflow.jpg
      - title: A Fresh Cup
        links:
          - url: http://afreshcup.com
            type: blog
        description: 
        screenshot_img_src: screenshots/ruby/afreshcup.jpg
      - title: RailsTips
        links:
          - url: http://www.railstips.org
            type: blog
        description: 
        screenshot_img_src: screenshots/ruby/railstips.jpg
      - title: PlanetRubyOnRails
        links:
          - url: http://planetrubyonrails.com
            type: blog
        description: 
        screenshot_img_src: screenshots/ruby/planetrubyonrails.jpg
      - title: Ruby5
        links:
          - url: http://ruby5.envylabs.com
            type: podcast
        description: 
        screenshot_img_src: screenshots/ruby/ruby5.jpg
      - title: GreenRuby
        links:
          - url: http://greenruby.org
            type: newsletter
        description: 
        screenshot_img_src: screenshots/ruby/greenruby.jpg
      - title: Monkey and Crow
        links:
          - url: http://monkeyandcrow.com
            type: blog
        description: 
        screenshot_img_src: screenshots/ruby/monkeyandcrow.jpg
      - title: Ruby Weekly
        links:
          - url: http://rubyweekly.com
            type: newsletter
        description: 
        screenshot_img_src: screenshots/ruby/rubyweekly.jpg
      - title: Arkency Blog
        links:
          - url: http://blog.arkency.com
            type: blog
        description: 
        screenshot_img_src: screenshots/ruby/arkency.jpg
      - title: Jakub Chodounský
        links:
          - url: http://chodounsky.net
            type: blog
        description: "Jakub's blog ..."
        screenshot_img_src: screenshots/ruby/chodounsky.jpg

  node:
    title: Node Resources
    description: TODO
    additional_stylesheets:
      - href: http://fonts.googleapis.com/css?family=Source+Sans+Pro
    styling:
      bg_color: "#1d1d1d"
      text_color: "#ccc"
      font_family: "'source-sans-pro', sans-serif"
      header:
        logo_img_src: logos/node.png
        bg_color: "#303030"
        text_color: "#ccc"
      resource_block:
        background_color: "rgba(255,255,255,0.1)"
    resources:
      - title: Node
        links:
          - url: http://nodejs.org
            type: site
        description: The official NodeJs web site.
        screenshot_img_src: screenshots/node/nodejs.jpg
